### ISSUE TITLE
 terraform apply errors davinci-oidc_sdk-ciam_passwordless_solution-pkg

### ISSUE THREAD

**Issue by hinespj** [pingidentity-developers-experience/ping-integration-example-packages#65] opened 2024-01-19 21:51 UTC
Error: Error deploying flow
│ 
│   with davinci_flow.change_password_subflow,
│   on davinci.tf line 296, in resource "davinci_flow" "change_password_subflow":
│  296: resource "davinci_flow" "change_password_subflow" {
│ 
│ This may indicate flow 'OOTB - Change Password - Subflow' contains unconfigured nodes.
╵
╷
│ Error: Unable to create connection. Error: status: 400, body: {"cause":null,"logLevel":"error","serviceName":null,"message":"The connector name entered is already associated with another connector. Enter a different name.","errorMessage":"The connector name entered is already associated with another connector. Enter a different name.","success":false,"httpResponseCode":400,"code":7000}
│ 
│   with davinci_connection.pingone_authentication,
│   on davinci.tf line 698, in resource "davinci_connection" "pingone_authentication":
│  698: resource "davinci_connection" "pingone_authentication" {
│ 
╵
╷
│ Error: Error when calling `CreateUserRoleAssignment`: The request could not be completed. One or more validation errors were in the request.
│ 
│   with pingone_role_assignment_user.admin_sso_environment_admin,
│   on resources.tf line 16, in resource "pingone_role_assignment_user" "admin_sso_environment_admin":
│   16: resource "pingone_role_assignment_user" "admin_sso_environment_admin" {
│ 
│ PingOne Error Details:
│ ID: 37fb7539-4a45-4223-9133-61cb713543f1
│ Code: INVALID_DATA
│ Message: The request could not be completed. One or more validation errors were in the request.
│ Details object: [{"code":"UNIQUENESS_VIOLATION","message":"May not assign duplicate Role","target":"role"}]

**Comment by michaelsanchez-pingidentity** [comment] 2024-01-19 22:03
The error for `CreateUserRoleAssignment` can be ignored. This is a known, anomalous error that has no impact. We're looking into the root cause next sprint. All the packages currently say this upon `terraform apply` but test successfully.

**Comment by michaelsanchez-pingidentity** [comment] 2024-01-19 23:43
@hinespj  Your connection error is probably valid. I just hit a similar error while making the provider updates. It looks like the solutions team are not bootstrapping one of the Ping connectors in the flow, so we no longer need to create it. I should have the updates to the CIAM passwordless package done today. I can send it to you when done if you need it ASAP.

**Comment by michaelsanchez-pingidentity** [comment] 2024-02-09 17:07
The root cause of the issue was found and resolved with a hotfix release this morning.

**Closed** 2024-02-09 17:08 UTC
Labels: bug
